export type CountryDial = { name: string; iso2: string; dialCode: string };

export const COUNTRY_DIALS: CountryDial[] = [
  { name: 'United Kingdom', iso2: 'GB', dialCode: '+44' },
  { name: 'Afghanistan', iso2: 'AF', dialCode: '+93' },
  { name: 'Albania', iso2: 'AL', dialCode: '+355' },
  { name: 'Australia', iso2: 'AU', dialCode: '+61' },
  { name: 'Bangladesh', iso2: 'BD', dialCode: '+880' },
  { name: 'Belgium', iso2: 'BE', dialCode: '+32' },
  { name: 'Brazil', iso2: 'BR', dialCode: '+55' },
  { name: 'Bulgaria', iso2: 'BG', dialCode: '+359' },
  { name: 'Canada', iso2: 'CA', dialCode: '+1' },
  { name: 'China', iso2: 'CN', dialCode: '+86' },
  { name: 'Colombia', iso2: 'CO', dialCode: '+57' },
  { name: 'Czechia', iso2: 'CZ', dialCode: '+420' },
  { name: 'Egypt', iso2: 'EG', dialCode: '+20' },
  { name: 'Ethiopia', iso2: 'ET', dialCode: '+251' },
  { name: 'France', iso2: 'FR', dialCode: '+33' },
  { name: 'Germany', iso2: 'DE', dialCode: '+49' },
  { name: 'Ghana', iso2: 'GH', dialCode: '+233' },
  { name: 'Greece', iso2: 'GR', dialCode: '+30' },
  { name: 'Hungary', iso2: 'HU', dialCode: '+36' },
  { name: 'India', iso2: 'IN', dialCode: '+91' },
  { name: 'Iran', iso2: 'IR', dialCode: '+98' },
  { name: 'Iraq', iso2: 'IQ', dialCode: '+964' },
  { name: 'Ireland', iso2: 'IE', dialCode: '+353' },
  { name: 'Italy', iso2: 'IT', dialCode: '+39' },
  { name: 'Jamaica', iso2: 'JM', dialCode: '+1' },
  { name: 'Kenya', iso2: 'KE', dialCode: '+254' },
  { name: 'Latvia', iso2: 'LV', dialCode: '+371' },
  { name: 'Lithuania', iso2: 'LT', dialCode: '+370' },
  { name: 'Mexico', iso2: 'MX', dialCode: '+52' },
  { name: 'Morocco', iso2: 'MA', dialCode: '+212' },
  { name: 'Nepal', iso2: 'NP', dialCode: '+977' },
  { name: 'Netherlands', iso2: 'NL', dialCode: '+31' },
  { name: 'New Zealand', iso2: 'NZ', dialCode: '+64' },
  { name: 'Nigeria', iso2: 'NG', dialCode: '+234' },
  { name: 'Pakistan', iso2: 'PK', dialCode: '+92' },
  { name: 'Philippines', iso2: 'PH', dialCode: '+63' },
  { name: 'Poland', iso2: 'PL', dialCode: '+48' },
  { name: 'Portugal', iso2: 'PT', dialCode: '+351' },
  { name: 'Romania', iso2: 'RO', dialCode: '+40' },
  { name: 'Slovakia', iso2: 'SK', dialCode: '+421' },
  { name: 'Somalia', iso2: 'SO', dialCode: '+252' },
  { name: 'South Africa', iso2: 'ZA', dialCode: '+27' },
  { name: 'Spain', iso2: 'ES', dialCode: '+34' },
  { name: 'Sri Lanka', iso2: 'LK', dialCode: '+94' },
  { name: 'Sudan', iso2: 'SD', dialCode: '+249' },
  { name: 'Syria', iso2: 'SY', dialCode: '+963' },
  { name: 'Turkey', iso2: 'TR', dialCode: '+90' },
  { name: 'Ukraine', iso2: 'UA', dialCode: '+380' },
  { name: 'United States', iso2: 'US', dialCode: '+1' },
  { name: 'Zimbabwe', iso2: 'ZW', dialCode: '+263' },
];
